name: Daily builds of changes to the TSConfig bases dir

# For testing
# on: push

# For production
on:
  schedule:
    - cron: "0 4 * * *"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://registry.npmjs.org"

      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.x

  
      # Build all the packages
      - name: Create packages for TSConfig JSONs
        run: deno run --allow-read --allow-write --allow-net scripts/create-npm-packages.ts
        
      # Deploy anything which has changed in the last day
      - run: |
         # Have commits been added in the last day?
         git log --pretty=format: --name-only --since="1 days ago"
         
         if [[ $(git log --pretty=format: --name-only --since="1 days ago") ]]; then
            git log --pretty=format: --name-only --since="1 days ago" bases | deno run --allow-read --allow-run --allow-env scripts/deploy-npm-packages.ts
         fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        name: 'Deploy built packages to NPM'


